name: Supra-Kernel
on:
  workflow_dispatch:
    inputs:
      DEVICE:
        description: 'Select the device for the build'
        required: true
        default: 'channel'
        type: choice
        options:
          - channel
          - ocean
          - river

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set Current Date
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Setting up the environment
        run: |
          sudo apt-get update -y
          sudo apt-get install gcc-aarch64-linux-gnu -y

      - name: Set Build Start Time
        id: start_time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Run build script
        run: |
          ./build.sh ${{ github.event.inputs.DEVICE }}

      - name: Set Build End Time
        id: end_time
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Calculate Build Duration
        id: build_duration
        run: |
          start_time=$(echo "${{ env.START_TIME }}")
          end_time=$(echo "${{ env.END_TIME }}")
          duration=$((end_time - start_time))
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          echo "BUILD_DURATION=${minutes} minutes and ${seconds} seconds." >> $GITHUB_ENV

      - name: Set Device Name
        id: device_name
        run: |
          if [ "${{ github.event.inputs.DEVICE }}" == "channel" ]; then
            echo "DEVICE_NAME=Moto G7 Play" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.DEVICE }}" == "ocean" ]; then
            echo "DEVICE_NAME=Moto G7 Power" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.DEVICE }}" == "river" ]; then
            echo "DEVICE_NAME=Moto G7" >> $GITHUB_ENV
          fi

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: Supra-${{ github.event.inputs.DEVICE }}*.zip
          message: |
             New version of Supra-Kernel for device ${{ env.DEVICE_NAME }} available!
             Build time: ${{ env.BUILD_DURATION }}
